### PR TITLE
modify parser function to extract core electrons from cp2k-9 outfile

### PR DESCRIPTION
**Pull request by mpougin**
adjustment of the workchain parser file to extract the number of core electrons from the cp2k-9 output file. I tested it on cp2k-8.1 and cp2k-9

### CODE REVIEW

**Comment by mpougin** [comment]
@yakutovicha can you help me here? I don't understand the problem

**Comment by mpougin** [comment]
The test that doesn`t produce an output and fails in the checks runs fine when I submit it on daint or eiger. When I run the pytest locally, I am getting this output:

`================================================================================================== test session starts ===================================================================================================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/miriam/aiida1/aiida-ddec, configfile: pyproject.toml
plugins: anyio-2.2.0, timeout-1.4.2, cov-2.12.1, asyncio-0.14.0
collected 1 item                                                                                                                                                                                                         

test_cp2k_ddec_h2o.py .                                                                                                                                                                                            [100%]

==================================================================================================== warnings summary ====================================================================================================
examples/test_cp2k_ddec_h2o.py::run_cp2k_ddec_h2o
  /home/miriam/anaconda3/envs/aiida/lib/python3.8/site-packages/aiida_testing/mock_code/_fixtures.py:143: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    assert isinstance(arg, collections.Iterable) and not isinstance(arg, str), \

examples/test_cp2k_ddec_h2o.py::run_cp2k_ddec_h2o
  /home/miriam/aiida1/aiida-ddec/aiida_ddec/utils/workchains.py:22: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    if (k in dct and isinstance(dct[k], dict) and isinstance(merge_dct[k], collections.Mapping)):

-- Docs: https://docs.pytest.org/en/stable/warnings.html

----------- coverage: platform linux, python 3.8.5-final-0 -----------
Name                                                                 Stmts   Miss  Cover
----------------------------------------------------------------------------------------
/home/miriam/aiida1/aiida-ddec/aiida_ddec/__init__.py                    2      0   100%
/home/miriam/aiida1/aiida-ddec/aiida_ddec/calculations/__init__.py      96     10    90%
/home/miriam/aiida1/aiida-ddec/aiida_ddec/parsers/__init__.py           31      5    84%
/home/miriam/aiida1/aiida-ddec/aiida_ddec/utils/__init__.py              3      0   100%
/home/miriam/aiida1/aiida-ddec/aiida_ddec/utils/workchains.py           32      1    97%
/home/miriam/aiida1/aiida-ddec/aiida_ddec/utils/xyzparser.py            38      0   100%
/home/miriam/aiida1/aiida-ddec/aiida_ddec/workchains/__init__.py         2      0   100%
/home/miriam/aiida1/aiida-ddec/aiida_ddec/workchains/cp2k_ddec.py       51      5    90%
----------------------------------------------------------------------------------------
TOTAL                                                                  255     21    92%

=================================================================================================== slowest durations ====================================================================================================
6.30s call     examples/test_cp2k_ddec_h2o.py::run_cp2k_ddec_h2o
4.58s setup    examples/test_cp2k_ddec_h2o.py::run_cp2k_ddec_h2o
0.19s teardown examples/test_cp2k_ddec_h2o.py::run_cp2k_ddec_h2o
============================================================================================= 1 passed, 2 warnings in 11.20s =============================================================================================`

Do I see it right that there's some issue with the mock-code here? @yakutovicha or @ltalirz can you help me here?

**Comment by yakutovicha** [comment]
hi @mpougin, I do not intend to work on this package, please proceed without my input.

**Comment by mpougin** [comment]
> hi @mpougin, I do not intend to work on this package, please proceed without my input.

okay

**Comment by ltalirz** [comment]
Hi @mpougin sorry for the very slow reply.

> When I run the pytest locally, I am get the assertion error, as the workchain doesn't produce the required output.

Hm... I guess this means the calculation actually fails? What is the assertion error?

There are essentially two possibilities here:
 1. The inputs of the test changed since the test data was generated. In this case aiida-testing will try to re-run cp2k locally to generate the new test data (see [here](https://github.com/lsmo-epfl/aiida-ddec#run-tests) for how to point to a local binary; note that if you change the label (e.g. to `cp2k-9.0`) you will also need to change it in the `conftest.py`).
 2. The inputs of the test did not change. In this case, the test failure indicates a problem in the parser.

**Comment by mpougin** [comment]
thanks for your feedback @ltalirz 
It seemed that the tests failed due to an error introduced in the latest cp2k release (https://github.com/aiidateam/aiida-cp2k/pull/151). It works fine now :)
Can you just give me a quick feedback if I merge now, or do I have to proceed as stated here: 
https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154 
Don't want to mess things up

**Review by ltalirz — APPROVED** [review]
thanks a lot for the update @mpougin !

The travis CI thing is a remnant of earlier times, I'll have a quick look whether I can get rid of it

**Comment by mpougin** [comment]
thanks for your help @ltalirz

**Pull request merged**
